enum class NativeMethod
{
    PUSH,
    POP,
    LENGTH,
    IS_EMPTY,
    CLEAR,
    CONTAINS,
    INDEX_OF,
    INSERT,
    REMOVE_AT,
    JOIN,
    REVERSE,
    FIRST,
    LAST,
    SLICE,
    COPY,
    CONCAT,
    SWAP,
    COUNT,
    EQUALS,
    LAST_INDEX_OF,
    TRIM,
    MIN,
    MAX,
    SUM,
    AVERAGE,
    FILL,
    INIT,

    ABS,
    LOG,
    LOG10,
    LOG2,
    MATH_MAX,
    MATH_MIN,
    MATH_AVERAGE,
    SIN,
    COS,
    TAN,
    ASIN,
    ACOS,
    ATAN,
    DEGREES,
    RADIANS,
    IS_ODD,
    IS_EVEN,
    IS_PRIME,
    GCD,
    LCM,
    NEXT_PRIME,
    SUM_DIGITS,
    FIBONACCI,
    PALINDROME,
    ROUND,
    PI,
    PRECISION,

    RANDOM_COLOR_RGB,
    RANDOM_COLOR_HEX,

    MATCH,

    SECOND_TO_MINUTE,
    SECOND_TO_HOUR,
    SECOND_TO_DAY,
    MINUTE_TO_SECOND,
    MINUTE_TO_HOUR,
    MINUTE_TO_DAY,
    HOUR_TO_SECOND,
    HOUR_TO_MINUTE,
    HOUR_TO_DAY,
    LEAP_YEAR,
    TODAY,

    BASE,

    TO_STRING,
    POW,
    SQRT,
    FACT,

    TO_INT,
    FLOOR,
    CEIL,

    BOOL_TO_INT,

    TO_NUMBER,
    UPPER,
    LOWER,
    CAPITALIZE,
    SWAPCASE,
    FIND,
    FIND_LAST,
    STR_FIRST,
    STR_LAST,
    STR_IS_EMPTY,
    STR_LENGTH,
    STARTS_WITH,
    ENDS_WITH,
    IS_NUMBER,
    IS_SPACE,
    IS_ALL_SPACES,
    REPLACE,
    STR_TRIM,
    TO_ARRAY,
    STR_COUNT,
    STR_SLICE,

    DICT_CONTAINS,
    DICT_REMOVE,
    DICT_LENGTH,
    DICT_KEYS,
    DICT_VALUES,
    DICT_POP,
    DICT_COPY,
    DICT_CLEAR,

    INPUT,
    RAND,
    RANDINT,
    ARRAY_INPUT,
    FORMAT,
    PRINTF,
    PRINT,
    PRINTLN,
    READ_FILE,
    WRITE_FILE,
    APPEND_FILE,
    ERASE_FILE,
    PARSE_JSON,
    TO_JSON,
    STRINGIFY,

    PROFILE_START,
    PROFILE_END,
    PROFILE_REPORT,
    PROFILE_RESET,

    EXISTS,
    IS_FILE,
    IS_DIRECTORY,
    MAKE_DIRECTORY,
    REMOVE_DIRECTORY,
    LIST_DIRECTORIES,
    LIST_FILES,
    SYSTEM,
    EXIT,
    DATE,
    OS_COPY,
    RENAME,

    PARSE_CSV,
    TO_CSV,

    INSTANCE_METHODS,
    TYPE,

    HTML_A,
    HTML_ADDRESS,
    HTML_AREA,
    HTML_ARTICLE,
    HTML_ASIDE,
    HTML_AUDIO,
    HTML_BASE,
    HTML_BLOCKQUOTE,
    HTML_BODY,
    HTML_BR,
    HTML_BUTTON,
    HTML_CANVAS,
    HTML_CAPTION,
    HTML_CITE,
    HTML_CODE,
    HTML_COL,
    HTML_COLGROUP,
    HTML_CONSTRUCT,
    HTML_DATALIST,
    HTML_DD,
    HTML_DEL,
    HTML_DIV,
    HTML_DL,
    HTML_DT,
    HTML_EM,
    HTML_EMBED,
    HTML_FIELDSET,
    HTML_FIGCAPTION,
    HTML_FIGURE,
    HTML_FOOTER,
    HTML_FORM,
    HTML_H1,
    HTML_H2,
    HTML_H3,
    HTML_H4,
    HTML_H5,
    HTML_H6,
    HTML_HEAD,
    HTML_HEADER,
    HTML_HR,
    HTML_IFRAME,
    HTML_IMG,
    HTML_INPUT,
    HTML_INS,
    HTML_LABEL,
    HTML_LEGEND,
    HTML_LI,
    HTML_LINK,
    HTML_MAIN,
    HTML_MAP,
    HTML_MARK,
    HTML_META,
    HTML_METER,
    HTML_NAV,
    HTML_OBJECT,
    HTML_OL,
    HTML_OPTGROUP,
    HTML_OPTION,
    HTML_OUTPUT,
    HTML_P,
    HTML_PARAM,
    HTML_PICTURE,
    HTML_PRE,
    HTML_PROGRESS,
    HTML_Q,
    HTML_SECTION,
    HTML_SELECT,
    HTML_SMALL,
    HTML_SOURCE,
    HTML_SPAN,
    HTML_STRONG,
    HTML_STYLE,
    HTML_SUB,
    HTML_SUP,
    HTML_TABLE,
    HTML_TBODY,
    HTML_TD,
    HTML_TEXTAREA,
    HTML_TFOOT,
    HTML_TH,
    HTML_THEAD,
    HTML_TIME,
    HTML_TITLE,
    HTML_TR,
    HTML_TRACK,
    HTML_UL,
    HTML_VIDEO,
    HTML_WBR,
    HTML_ATTR,
    HTML_APPEND,

    GUI_INIT,
    GUI_START,
    GUI_DRAW_TEXT,
    GUI_DRAW_RECT,
    GUI_DRAW_CIRCLE,
    GUI_LOAD_TEXTURE,
    GUI_DRAW_TEXTURE,
    GUI_CLEAR
};

#include "native/array.hpp"
#include "native/conversion.hpp"
#include "native/dict.hpp"
#include "native/file.hpp"
#include "native/global.hpp"
#include "native/math.hpp"
#include "native/profiler.hpp"
#include "native/random.hpp"
#include "native/string.hpp"
#include "native/text.hpp"
#include "native/encode.hpp"
#include "native/regex.hpp"
#include "native/time.hpp"
#include "native/web.hpp"
#include "native/graphics.hpp"